
################################################################################
# Functions
################################################################################

do_preprocessing_mothers <- function(
    TCAM,
    cross_phenotypes,
    cross_selection
) {
  
  # Prepare the TCAM table generated by TCAM.ipynb
  rownames(TCAM) <- TCAM$X
  TCAM <- subset(TCAM, select = -X)
  
  # Retain only mothers present in the TCAM table
  cross_phenotypes <- cross_phenotypes[
    cross_phenotypes$next_id_mother %in% rownames(TCAM),
  ]
  
  # Recode parity values of 2 or greater as 2
  cross_phenotypes$mother_birthcard_parity <- ifelse(
    is.na(cross_phenotypes$mother_birthcard_parity),
    NA,
    ifelse(
      cross_phenotypes$mother_birthcard_parity >= 2,
      2,
      cross_phenotypes$mother_birthcard_parity
    )
  )
  
  rownames(cross_phenotypes) <- cross_phenotypes$next_id_mother
  
  # Select variables included in the maternal TCAM analysis
  mother_cross_selection <- cross_selection[
    cross_selection$TCAM_mothers == 1 &
      !is.na(cross_selection$TCAM_mothers),
  ]
  
  column_names <- mother_cross_selection[[1]]
  
  mother_cross_phenotypes <- cross_phenotypes %>%
    select(all_of(column_names))
  
  # Remove identifier and family-structure variables
  to_exclude <- c(
    "FAMILY",
    "next_id_mother",
    "next_id_infant",
    "next_id_partner",
    "infant_relations",
    "sibling_number",
    "twin_pair"
  )
  
  mother_cross_phenotypes_filtered <- mother_cross_phenotypes[
    ,
    !(colnames(mother_cross_phenotypes) %in% to_exclude),
    drop = FALSE
  ]
  
  # Ensure identical sample order in TCAM and phenotype tables
  common_samples <- intersect(
    rownames(TCAM),
    rownames(mother_cross_phenotypes_filtered)
  )
  
  TCAM <- TCAM[common_samples, , drop = FALSE]
  
  mother_cross_phenotypes_filtered <-
    mother_cross_phenotypes_filtered[
      common_samples,
      ,
      drop = FALSE
    ]
  
  return(
    list(
      TCAM = TCAM,
      phenotypes = mother_cross_phenotypes_filtered
    )
  )
}


do_permanova_simple <- function(
    processed_data,
    permutation_num = 10000
) {
  
  TCAM <- processed_data$TCAM
  phenotypes <- processed_data$phenotypes
  
  # Generate the Euclidean distance matrix from the TCAM factors
  distance_matrix <- vegdist(
    TCAM,
    method = "euclidean"
  )
  
  distance_matrix <- as.matrix(distance_matrix)
  
  # Initialise the PERMANOVA results table
  adonis_results_raw <- data.frame(
    Df = rep(NA_real_, ncol(phenotypes)),
    F = rep(NA_real_, ncol(phenotypes)),
    R2 = rep(NA_real_, ncol(phenotypes)),
    p_value = rep(NA_real_, ncol(phenotypes)),
    row.names = colnames(phenotypes)
  )
  
  for (i in seq_len(ncol(phenotypes))) {
    
    phenotype_name <- colnames(phenotypes)[i]
    phenotype_vector <- phenotypes[[i]]
    
    # Retain samples with non-missing phenotype values
    complete_samples <- rownames(phenotypes)[
      !is.na(phenotype_vector)
    ]
    
    distmat_cleaned <- distance_matrix[
      complete_samples,
      complete_samples,
      drop = FALSE
    ]
    
    phenotype_cleaned <- phenotypes[
      complete_samples,
      phenotype_name,
      drop = TRUE
    ]
    
    # Skip variables with insufficient observations or no variation
    if (
      length(phenotype_cleaned) < 3 ||
      length(unique(phenotype_cleaned)) < 2
    ) {
      warning(
        paste(
          "Skipping",
          phenotype_name,
          "because it has insufficient observations or variation."
        )
      )
      
      next
    }
    
    # Run univariable PERMANOVA
    adonis_result <- adonis2(
      distmat_cleaned ~ phenotype_cleaned,
      permutations = permutation_num,
      parallel = 8,
      na.action = na.fail,
      by = "terms"
    )
    
    # Save results
    adonis_results_raw[i, ] <- c(
      adonis_result$Df[1],
      adonis_result$F[1],
      adonis_result$R2[1],
      adonis_result$`Pr(>F)`[1]
    )
  }
  
  return(adonis_results_raw)
}



phenotype_directory <- paste0(
  "/Users/trishlasinha/Desktop/LLNEXT/Analysis/phenotypes"
)

results_directory <- paste0(
  "/Users/trishlasinha/Desktop/LLNEXT/Analysis/",
  "results/adonis_per_timepoint"
)


cross_phenotypes <- read.delim(
  file.path(
    phenotype_directory,
    "masterfile_cross_sectional_2023_11_15.txt"
  )
)

cross_selection_mothers <- read.delim(
  file.path(
    phenotype_directory,
    paste0(
      "masterfile_cross_sectional_selection_",
      "AFTER_correlation_&_correction_10_07_2024.txt"
    )
  )
)

TCAM_mother_P12_B_M3 <- read.delim(
  file.path(
    results_directory,
    "old/TCAM_mother_P12_B_M3.txt"
  ),
  sep = ","
)


processed_mother_P12_B_M3 <- do_preprocessing_mothers(
  TCAM = TCAM_mother_P12_B_M3,
  cross_phenotypes = cross_phenotypes,
  cross_selection = cross_selection_mothers
)

################################################################################
# Maternal PERMANOVA analysis
################################################################################

set.seed(123)

permanova_simple_mother_P12_B_M3 <- do_permanova_simple(
  processed_data = processed_mother_P12_B_M3,
  permutation_num = 10000
)

permanova_simple_mother_P12_B_M3$Phenotype <-
  rownames(permanova_simple_mother_P12_B_M3)

################################################################################
# Save results
################################################################################

write.table(
  permanova_simple_mother_P12_B_M3,
  file = file.path(
    results_directory,
    "result_adonis_tcam_mothers_10000_perm.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)